export const types = {
  FETCH_BOARDS_START: 'FETCH_BOARDS_START',
  FETCH_BOARDS_SUCCESS: 'FETCH_BOARDS_SUCCESS',
  FETCH_BOARDS_ERROR: 'FETCH_BOARDS_SUCCESS',

  FETCH_BOARD_BY_ID_START: 'FETCH_BOARD_BY_ID_START',
  FETCH_BOARD_BY_ID_SUCCESS: 'FETCH_BOARD_BY_ID_SUCCESS',
  FETCH_BOARD_BY_ID_ERROR: 'FETCH_BOARD_BY_ID_SUCCESS',

  ADD_BOARD_START: "ADD_BOARD_START",
  ADD_BOARD_SUCCESS: "ADD_BOARD_SUCCESS",
  ADD_BOARD_ERROR: "ADD_BOARD_ERROR",

  DELETE_BOARD_START: "DELETE_BOARD_START",
  DELETE_BOARD_SUCCESS: "DELETE_BOARD_SUCCESS",
  DELETE_BOARD_ERROR: "DELETE_BOARD_ERROR",

  ADD_LIST_START: "ADD_LIST_START",
  ADD_LIST_SUCCESS: "ADD_LIST_SUCCESS",
  ADD_LIST_ERROR: "ADD_LIST_ERROR",

  DELETE_LIST_START: "DELETE_LIST_START",
  DELETE_LIST_SUCCESS: "DELETE_LIST_SUCCESS",
  DELETE_LIST_ERROR: "DELETE_LIST_ERROR",

  ADD_TASK_START: "ADD_TASK_START",
  ADD_TASK_SUCCESS: "ADD_TASK_SUCCESS",
  ADD_TASK_ERROR: "ADD_TASK_ERROR",

  ADD_BOARD_LIST: "ADD_BOARD_LIST",
  ADD_BOARD_TASK: "ADD_BOARD_TASK",
  CHANGE_TASK_STATUS: "CHANGE_TASK_STATUS",
  ADD_TASK_TO_ANOTHER_LIST: "ADD_TASK_TO_ANOTHER_LIST"
};
